apiVersion: apps/v1
kind: Deployment
metadata:
  name: karsajobs-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: karsajobs-ui
  template:
    metadata:
      labels:
        app: karsajobs-ui
    spec:
      containers:
        - name: karsajobs-ui
          image: takathena/karsajobs-ui:latest
          ports:
            - containerPort: 80
          env:
            - name: VUE_APP_BACKEND
              value: "http://192.168.49.2:30081"