apiVersion: apps/v1
kind: Deployment
metadata:
  name: karsajobs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: karsajobs
  template:
    metadata:
      labels:
        app: karsajobs
    spec:
      containers:
        - name: karsajobs
          image: takathena/karsajobs:latest
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_HOST
              value: "mongo-service"
            - name: MONGO_USER
              value: "mongouser"
            - name: MONGO_PASS
              value: "mongopass"