apiVersion: v1
kind: Service
metadata:
  name: karsajobs-ui-service
spec:
  type: NodePort
  selector:
    app: karsajobs-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080